In [2]:
import pandas as pd

In [3]:
df1 = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "Dominic", "Exo", "Fedora", "Galvin", "Charlie"], 
    "Age": [23,22,26,22,31,19,19,23],
    "City": ["LA", "Miami", "Chicago", "LA", "Houston", "Miami", "Vegas", "DC"]
}, index=["#1", "#2", "#3", "#4", "#5", "#6", "#7", "#8"])

In [4]:
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]], columns=["A","B","C"])

In [5]:
df1.shape

(8, 3)

In [6]:
df.shape

(3, 3)

In [7]:
coffee = pd.read_csv('./warmup-data/coffee.csv')

In [8]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [20]:
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          10
1      Monday       Latte          10
2     Tuesday    Espresso          10
3     Tuesday       Latte          10
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [24]:
coffee.loc[coffee["Units Sold"] >= 40]

         Day Coffee Type  Units Sold
6   Thursday    Espresso          40
8     Friday    Espresso          45
10  Saturday    Espresso          45
12    Sunday    Espresso          45